server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: fanmaisystem
  
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fanmaisystem?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  
  # Thymeleaf 配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false  # 开发环境关闭缓存，生产环境改为true
  
  # 静态资源路径
  web:
    resources:
      static-locations: classpath:/static/

# MyBatis 配置
mybatis:
  # 指定 mapper.xml 文件位置
  mapper-locations: classpath:mapper/*.xml
  # 指定实体类包路径
  type-aliases-package: com.dhee.fanmaisystem.entity
  configuration:
    # 开启驼峰命名转换
    map-underscore-to-camel-case: true
    # 日志实现
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 日志配置
logging:
  level:
    com.dhee.fanmaisystem: debug
    org.springframework: info

